---
- name: Install packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - httpd24
    - php70
    - mysql56-server
    - php70-mysqlnd
  become: yes

- mame: Adjust the listening port of the appache
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "Listen {{http_port}}"
    regexp: ^Listen \d+
    state: present
  become: yes
  notify: restart httpd
  
- name: Enable httpd
  service: 
    name: httpd 
    state: started
    enabled: yes
  become: yes

- name: Copy the latest version of Wordpress to the server.
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    remote_src: yes
    owner: apache
    group: apache
    extra_opts: --strip-components=1
  become: yes

- name: Get salts for the wordpress configuration file
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: salt
  delegate_to: localhost
  run_once: yes

- name: Pupulate the Wordpress configuration file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: apache
    group: apache
  become: yes

