---
- name: Bastion Clients
  hosts: "\
    ~tag_aws_cloudformation_stack_name_{{ aws_mgmt_stack }}.*:&\
    security_group_{{ aws_mgmt_ansible_secgrp.GroupName|replace('-', '_') }}:&\
    security_group_{{ aws_mgmt_bastion_secgrp.GroupName|replace('-', '_') }}"
  vars_files:
    - ../aws_cloudformation.yml
    - vars/aws_lookups.yml
  roles:
    - bastion-client

- name: Bastion Host
  hosts: "\
    ~tag_aws_cloudformation_stack_name_{{ aws_mgmt_stack }}.*:&\
    security_group_{{ aws_mgmt_ansible_secgrp.GroupName|replace('-', '_') }}:&\
    tag_aws_cloudformation_logical_id_WPBastionAutoScalingGroup"
  vars_files:
    - ../aws_cloudformation.yml
    - vars/aws_lookups.yml
  roles:
    - role: bastion-host
      ip_range: "{{ aws_bastion_range }}"

- name: Wordpress Server
  hosts: "\
    ~tag_aws_cloudformation_stack_name_{{ aws_mgmt_stack }}.*:&\
    security_group_{{ aws_mgmt_ansible_secgrp.GroupName|replace('-', '_') }}:&\
    tag_aws_cloudformation_logical_id_WPWebAutoScalingGroup"
  vars_files:
    - ../aws_cloudformation.yml
    - vars/aws_lookups.yml
  roles:
    - role: wordpress-server
      db_name: "{{aws_web_db_credentials.name}}"
      db_user: "{{aws_web_db_credentials.user}}"
      db_pass: "{{aws_web_db_credentials.pass}}"
      db_host: "{{aws_web_db_credentials.host}}"
      http_port: "{{aws_web_port}}"

