---
- hosts: "security_group_{{ aws_mgmt_ansible_secgrp.GroupName|replace('-', '_') }}:&~tag_aws_cloudformation_stack_name_{{ aws_mgmt_stack }}.*"
  vars_files:
    - ../aws_cloudformation.yml
    - vars/aws_lookups.yml
  roles:
    - bastion-client
