---
- name: Bastion Clients
  hosts: "\
    ~tag_aws_cloudformation_stack_name_{{ aws_mgmt_stack }}.*:&\
    security_group_{{ aws_mgmt_ansible_secgrp.GroupName|replace('-', '_') }}:&\
    security_group_{{ aws_mgmt_bastion_secgrp.GroupName|replace('-', '_') }}"
  vars_files:
    - ../aws_cloudformation.yml
    - vars/aws_lookups.yml
  roles:
    - bastion-client

- name: Bastion Host
  hosts: "\
    ~tag_aws_cloudformation_stack_name_{{ aws_mgmt_stack }}.*:&\
    security_group_{{ aws_mgmt_ansible_secgrp.GroupName|replace('-', '_') }}:&\
    tag_aws_cloudformation_logical_id_WPBastionAutoScalingGroup"
  vars_files:
    - ../aws_cloudformation.yml
    - vars/aws_lookups.yml
  roles:
    - role: bastion-host
      ip_range: "{{ aws_bastion_range }}"
