---
- name: Allow Access to the ansible user only from the local network
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "AllowUsers {{ansible_user}}@{{ip_range}}"
  become: yes
  notify: restart sshd
